name: Signup Form Link

on: pull_request

jobs:
  signup_form_link:
    runs-on: ubuntu-latest
    name: Provide contributors with a link to the signup form 
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment on the PR with a signup form link
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for creating this PR. Please submit your details on [this form](http://aka.ms/golclinics-signup-1)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}